import Foundation

/// The constellation figures, drawn for this app.
///
/// **Provenance (invariant 5):** the *drawings are ours.* Which stars
/// belong to which constellation is ancient common knowledge — Ptolemy's
/// Almagest carries the same membership — and the choice of which pairs
/// to join was authored by hand for this app, against the vendored
/// Hipparcos subset, with no external stick-figure dataset consulted.
/// That authorship is what keeps the layer licence-free where every
/// published figure set was not. Twenty-nine figures: the zodiac twelve
/// and the flagships of the northern sky, Draco among them because
/// Thuban held the builders' pole.
///
/// Generated by `scripts/generate_constellation_lines.py` — edit the
/// figures there, where every star reference is checked against the
/// catalogue, rather than editing HIP numbers here.
public struct ConstellationFigure: Sendable {

    public let name: String
    /// Pairs of HIP identifiers; each pair is one drawn line.
    public let segments: [(Int, Int)]

    public static let all: [ConstellationFigure] = [
        ConstellationFigure(name: "Andromeda", segments: [
            (677, 3092), (3092, 5447), (5447, 9640)
        ]),
        ConstellationFigure(name: "Aquarius", segments: [
            (106278, 109074), (109074, 110395), (110395, 111497), (109074, 110003),
            (110003, 112961), (112961, 113136), (106278, 102618)
        ]),
        ConstellationFigure(name: "Aquila", segments: [
            (97278, 97649), (97649, 98036), (93747, 95501), (95501, 93805),
            (97649, 95501)
        ]),
        ConstellationFigure(name: "Aries", segments: [
            (9884, 8903), (8903, 8832)
        ]),
        ConstellationFigure(name: "Auriga", segments: [
            (24608, 28360), (28360, 28380), (28380, 25428), (25428, 23015),
            (23015, 23416), (23416, 24608)
        ]),
        ConstellationFigure(name: "Boötes", segments: [
            (69673, 72105), (72105, 74666), (74666, 73555), (73555, 71075),
            (71075, 71053), (71053, 69673), (69673, 67927)
        ]),
        ConstellationFigure(name: "Cancer", segments: [
            (40526, 42911), (42911, 42806), (42911, 44066)
        ]),
        ConstellationFigure(name: "Canis Major", segments: [
            (32349, 30324), (32349, 33977), (33977, 34444), (34444, 33579),
            (34444, 35904)
        ]),
        ConstellationFigure(name: "Canis Minor", segments: [
            (37279, 36188)
        ]),
        ConstellationFigure(name: "Capricornus", segments: [
            (100064, 100345), (100345, 102485), (102485, 102978), (102978, 105881),
            (105881, 106985), (106985, 107556), (107556, 104139), (104139, 100064)
        ]),
        ConstellationFigure(name: "Cassiopeia", segments: [
            (746, 3179), (3179, 4427), (4427, 6686), (6686, 8886)
        ]),
        ConstellationFigure(name: "Cepheus", segments: [
            (105199, 106032), (106032, 116727), (116727, 112724), (112724, 109492),
            (109492, 105199)
        ]),
        ConstellationFigure(name: "Corona Borealis", segments: [
            (76127, 75695), (75695, 76267), (76267, 76952), (76952, 77512),
            (77512, 78159)
        ]),
        ConstellationFigure(name: "Cygnus", segments: [
            (102098, 100453), (100453, 95947), (102488, 100453), (100453, 97165)
        ]),
        ConstellationFigure(name: "Draco", segments: [
            (56211, 61281), (61281, 68756), (68756, 75458), (75458, 80331),
            (80331, 83895), (83895, 94376), (94376, 97433), (83895, 87585),
            (85670, 87833), (87833, 85819), (85819, 87585), (87585, 85670)
        ]),
        ConstellationFigure(name: "Gemini", segments: [
            (36850, 35550), (35550, 31681), (37826, 35550), (35550, 32246),
            (32246, 30343), (30343, 29655)
        ]),
        ConstellationFigure(name: "Leo", segments: [
            (49669, 49583), (49583, 50583), (50583, 50335), (50335, 48455),
            (48455, 47908), (49669, 54879), (54879, 57632), (57632, 54872),
            (54872, 49583), (54872, 54879)
        ]),
        ConstellationFigure(name: "Libra", segments: [
            (72622, 74785), (74785, 76333), (76333, 72622)
        ]),
        ConstellationFigure(name: "Lyra", segments: [
            (91262, 92791), (92791, 92420), (92420, 93194), (93194, 93017),
            (93017, 92791)
        ]),
        ConstellationFigure(name: "Orion", segments: [
            (26207, 27989), (27989, 26727), (26727, 27366), (27366, 24436),
            (24436, 25930), (25930, 25336), (25336, 26207), (26727, 26311),
            (26311, 25930), (27989, 25336)
        ]),
        ConstellationFigure(name: "Pegasus", segments: [
            (113963, 113881), (113881, 677), (677, 1067), (1067, 113963),
            (113963, 112029), (112029, 109427), (109427, 107315), (113881, 112158),
            (112158, 107354)
        ]),
        ConstellationFigure(name: "Perseus", segments: [
            (15863, 14328), (14328, 13268), (15863, 17358), (17358, 18532),
            (18532, 18246), (15863, 14668), (14668, 14576), (14576, 14354)
        ]),
        ConstellationFigure(name: "Pisces", segments: [
            (114971, 113889), (113889, 116928), (116928, 115830), (115830, 114971),
            (9487, 7007), (7007, 4906), (4906, 3786), (3786, 118268),
            (118268, 115830), (9487, 8198), (8198, 7097)
        ]),
        ConstellationFigure(name: "Sagittarius", segments: [
            (88635, 89931), (89931, 90185), (90185, 93506), (93506, 93864),
            (93864, 92855), (92855, 92041), (92041, 90496), (90496, 89931),
            (93506, 92041)
        ]),
        ConstellationFigure(name: "Scorpius", segments: [
            (78401, 80763), (80763, 81266), (81266, 82396), (82396, 82514),
            (82514, 82671), (82671, 84143), (84143, 86228), (86228, 87073),
            (87073, 86670), (86670, 85927), (85696, 85927), (78820, 78401),
            (78401, 78265)
        ]),
        ConstellationFigure(name: "Taurus", segments: [
            (20205, 20455), (20455, 20889), (20889, 25428), (20205, 20894),
            (20894, 21421), (21421, 26451)
        ]),
        ConstellationFigure(name: "Ursa Major", segments: [
            (67301, 65378), (65378, 62956), (62956, 59774), (59774, 54061),
            (54061, 53910), (53910, 58001), (58001, 59774)
        ]),
        ConstellationFigure(name: "Ursa Minor", segments: [
            (11767, 85822), (85822, 82080), (82080, 77055), (77055, 72607),
            (72607, 75097), (75097, 79822), (79822, 77055)
        ]),
        ConstellationFigure(name: "Virgo", segments: [
            (65474, 61941), (61941, 60129), (60129, 57757), (61941, 63090),
            (63090, 63608), (65474, 66249), (66249, 63090)
        ])
    ]
}
